package api.contracts.base;

public enum ErrorCodes {
    UNAUTHENTICATED,
    ACCESS_DENIED,
    GENERAL_ERROR,
    NOT_FOUND,
    VALIDATION_ERROR,
    LOW_BALANCE,
    DUPLICATE_EMAIL,
    DUPLICATE_USERNAME,
    INCORRECT_EMAIL
}
