package api.contracts.base;

public enum ErrorCodes {
    GENERAL_ERROR,
    AUTHENTICATION_ERROR,
    NOT_FOUND,
    VALIDATION_ERROR,
    LOW_BALANCE,
    DUPLICATE_EMAIL,
    DUPLICATE_USERNAME,
    BAD_REQUEST,
    LOCKING_ERROR,
    INCORRECT_EMAIL
}
